### ISSUE TITLE
Prison Mines not working

### ISSUE THREAD

**Issue by Darkknights22** [faizaand/Prison#209]
Hi,

I want to use your prison plugin so I installed it and did everything. When I did the command '/mines' it said 'Mines are disabled'.

I went and check in the config and it said that mines were enabled. Could I please have some help ASAP.

**Comment by DylanFPS** [comment]
Is anything happening in the log?

_Note that there might be an issue caused with the metrics -- @SirFaizdat is yet to address the issue so it might be a possible reason why. It's rather unlikely though..._

**Comment by Darkknights22** [comment]
In the console log, nothing is happening.

**Comment by DylanFPS** [comment]
Sorry for not getting back to you. Can you please try again now that we've fixed the metrics?

**Comment by faizaand** [comment]
I'm going to close this for inactivity. Please reopen the ticket if the problem persists.

**Comment by ItzTomeeee** [comment]
Yes I'm having the same problem?
