### ISSUE TITLE
Rankup Issue

### ISSUE THREAD

**Issue by Waffles2112** [faizaand/Prison#210]
When a player attempts to rankup after the second rank, it says they cant rankup to the max rank, but the next rank isnt the max rank, it skips all the ranks inbetween the 2nd rank and max rank

After ranking up twice, and ending up on rank D3, player attempts to rankup to D2, but instead says they cant rankup to A rank (max rank), and when tested with the amount of money needed for A rank, it skips all the ranks from D2 - A1, and goes straight to A

Rankup twice, attempt to rankup again, see it skip

Is problematic, as people have issues ranking up because of this, and i cant fix it on my own

**Comment by DylanFPS** [comment]
Don't worry, this is a common problem. Send me your rank files over and
tell me your desired rank up order and I'll fix your files

>

**Comment by Waffles2112** [comment]
[ranks.zip](https://github.com/SirFaizdat/Prison/files/998842/ranks.zip)
i have multiverse enabled if it makes a difference

**Comment by DylanFPS** [comment]
What is the order for ranking up supposed to be?

**Comment by Waffles2112** [comment]
D4, D3, D2, D1, D, C4, C3, C2, C1, C, B4, B3, B2, B1, B, A4, A3, A2, A1, A

**Comment by DylanFPS** [comment]
Thanks. I'll have a look at these tomorrow

**Comment by DylanFPS** [comment]
Your rank files seem okay -- please check that you have groups setup in your permissions plugin with *the same name as the rank*

**Comment by Waffles2112** [comment]
i did
i've been using ur plugin for while now
its just recently been doing this
i know the perm plugin isnt bad/wrong

**Comment by DylanFPS** [comment]
In which case this is a bug, and I will use your ranks to attempt to
resolve the issue. Please downgrade to the last version that worked and
I'll do my best to fix this bug.

**Comment by Waffles2112** [comment]
okay
