### ISSUE TITLE
Cannot be load in 1.10-1.11

### ISSUE THREAD

**Issue by lightda104530** [faizaand/Prison#217]
The plugin cannot be loaded in 1.10-1.11

**Comment by faizaand** [comment]
Is there any error message in the console?

**Comment by CarThax08** [comment]
For me the error it gives is Could not load 'plugins/Prison.jar' in folder 'plugins'.   You got my error and here is some proof.   
![screen shot 2017-08-23 at 12 20 14 am](https://user-images.githubusercontent.com/30299999/29598513-4f77c9da-8797-11e7-804f-8b67788503d1.png) It is a screenshot.

**Comment by faizaand** [comment]
@CarThax08 Can you give me the whole stack trace?

**Comment by CarThax08** [comment]
How do I do that???

**Comment by faizaand** [comment]
The whole server startup log. 

_Sent from my Samsung SM-G950U using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by CarThax08** [comment]
Where is that???

**Comment by CarThax08** [comment]
I tried in 1.9 and it also didn't work

**Comment by faizaand** [comment]
You have Vault and WorldEdit installed?

**Comment by CarThax08** [comment]
yes I just installed them and it worked!!!
