### ISSUE TITLE
"Mines are disabled", "Ranks are disabled" ... They are both enabled...

### ISSUE THREAD

**Issue by MrTrollAlex** [faizaand/Prison#219]
For some reason...When I started up my server today, the prison 2 plugin just started doing some weird stuff, like saying that mines and ranks were disabled, when in the config, both of them were enabled. This just happened randomly and I don't know the cause of it. It worked before but now it just stopped....
Please if there is a fix, please tell me. I checked all of the other posts on here and:
I have spigot and PermissionsEX so... I don't know the problem...
Here is my config:

#======= Prison 2.0 Configuration =======#
#           (C) 2016 SirFaizdat          #
#========================================#

server-prefix: "&4Prison &7>"
check-updates: true
opt-out: false

# Multiworld prohibits players from using prison commands in worlds not listed below.
# It is useful for servers that want to designate certain worlds towards prison.
# To use this feature, set multiworld to true and add the desired worlds in world-list.
multiworld: false
world-list: [mines]

# The enable block tells Prison whether or not to enable a component.
# Changes in this block will not take effect until the SERVER is reloaded or restarted.
enable:
  mines: true
  ranks: true
  autosmelt: true
  autoblock: true

# Mines Settings
reset-time: 10
reset-warnings: [10,5,1]
reset-warning-message: "&7Mines are going to reset in &3<mins> minutes&7."
reset-broadcast-message: "&3All mines have been reset."
fill-mode: true
async-reset: true

# Ranks Settings
fireworks-on-rankup: true

# Autosmelt Setings
flames-on-autosmelt: true

**Comment by faizaand** [comment]
Did you check the console logs for errors?

**Comment by MrTrollAlex** [comment]
yes, there were no errors just it saying that I issued the command /mines or /ranks

**Comment by GoodByeNerd** [comment]
I also have the same problem. Pls help!

**Comment by CarThax08** [comment]
yeah me too

**Comment by CarThax08** [comment]
I had an error...

[20:19:26 ERROR]: Error occurred while enabling Prison v2.4.1 (Is it up to date?)

**Comment by faizaand** [comment]
@CarThax08 Are you sure you have the plugin set up correctly? You must have Vault, WorldEdit, and a permissions and economy plugin such as LuckPerms for permission and Essentials

**Comment by PlayLikeJeppa** [comment]
I have the same problem! What should I do? Can anything help me? Please

**Comment by CarThax08** [comment]
PlayLikeJeppa, Did you do what faizaand told me to do? It worked for me.
