### ISSUE TITLE
Commands disabled?

### ISSUE THREAD

**Issue by MLGFarmerElite** [faizaand/Prison#223]
Before you read this, I'd like to disclose I'm a complete noob at this sort of thing.

### What's the problem?

When I do any commands related to the plugin, aside from /prison, it simply tells me it is disabled. 

Example :  /ranks returns "Ranks are disabled" 

### What's happening?

Commands are disabled?

### How do we recreate the problem?

I'm running Spigot 1.8 on my server and using the latest version of Prisons 2

### Anything else you need to tell us?

Here's my config

#======= Prison 2.0 Configuration =======#
#           (C) 2016 SirFaizdat          #
#========================================#

server-prefix: "&4Prison &7>"
check-updates: true
opt-out: false

# Multiworld prohibits players from using prison commands in worlds not listed below.
# It is useful for servers that want to designate certain worlds towards prison.
# To use this feature, set multiworld to true and add the desired worlds in world-list.
multiworld: true
world-list: [prisonsmap]

# The enable block tells Prison whether or not to enable a component.
# Changes in this block will not take effect until the SERVER is reloaded or restarted.
enable:
  mines: true
  ranks: true
  autosmelt: true
  autoblock: true
  json: true

# Mines Settings
reset-time: 10
reset-warnings: [10,5,1]
reset-warning-message: "&8[&6HAZMATMC&8] &c&L>>> &7Mines are going to reset in &3<mins> minutes&7."
reset-broadcast-message: "&8[&6HAZMATMC&8] &c&L>>> &3All mines have been reset."
fill-mode: true
async-reset: true

# Ranks Settings
fireworks-on-rankup: true

# Autosmelt Setings
flames-on-autosmelt: true

**Comment by faizaand** [comment]
Did you install the dependencies, Vault and WorldEdit, as well as a permissions and economy plugin (such as PermissionsEx and Essentials)?

**Comment by MLGFarmerElite** [comment]
Does EssentialsX count as Essentials? If so then yes, I've got all the plugins added to my server.
