### ISSUE TITLE
Plugin Unable To Receive 

### ISSUE THREAD

**Issue by YoloBausMC** [faizaand/Prison#225]
Hi I am trying to load version 2.4.1 on a spigot 1.12.2 prison server.
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
15.10 10:19:35 [Server] INFO ... 6 more
15.10 10:19:35 [Server] ERROR Could not load 'plugins/Prison.jar' in folder 'plugins'
15.10 10:19:35 [Server] INFO org.bukkit.plugin.UnknownDependencyException: Vault
This pops up and prison server does not recognise plugin

**Comment by DylanFPS** [comment]
You don't have Vault.
